Logging:
    LogLevel:
        # Trace, Debug, Information, Warning, or Error
        Default: Trace

MeadowCloud:
    Enabled: true
    EnableUpdates: true

HealthMetrics:
    # Enable Health Metrics
#    Enabled: true

    # How often to send metrics to Meadow.Cloud (in minutes)
#    Interval: 15